USE [master]
GO

/****** Object:  Database [BeagleRescue]    Script Date: 11/1/2023 1:23:18 PM ******/
CREATE DATABASE [BeagleRescue]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeagleRescue', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019EX\MSSQL\DATA\BeagleRescue.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BeagleRescue_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019EX\MSSQL\DATA\BeagleRescue_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeagleRescue].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BeagleRescue] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BeagleRescue] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BeagleRescue] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BeagleRescue] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BeagleRescue] SET ARITHABORT OFF 
GO

ALTER DATABASE [BeagleRescue] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BeagleRescue] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BeagleRescue] SET AUTO_UPDATE_STATISTICS OFF 
GO

ALTER DATABASE [BeagleRescue] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BeagleRescue] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BeagleRescue] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BeagleRescue] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BeagleRescue] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BeagleRescue] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BeagleRescue] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BeagleRescue] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BeagleRescue] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BeagleRescue] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BeagleRescue] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BeagleRescue] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BeagleRescue] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BeagleRescue] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BeagleRescue] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BeagleRescue] SET  MULTI_USER 
GO

ALTER DATABASE [BeagleRescue] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [BeagleRescue] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BeagleRescue] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BeagleRescue] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BeagleRescue] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BeagleRescue] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BeagleRescue] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BeagleRescue] SET  READ_WRITE 
GO

